### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by casecamp** [postmodern/sinatra-json#1]
Hi When I try to install sinatra-json , I am getting the following error

```
   sinatra-json was resolved to 0.1.0, which depends on
      sinatra (~> 1.0)
```

I have installed sinatra from master `gem "sinatra", github: 'sinatra/sinatra'`

**Comment by postmodern** [comment]
That would be because sinatra master is currently at [2.0.0.beta2](https://github.com/sinatra/sinatra/blob/master/lib/sinatra/version.rb). Use the stable version of sinatra from rubygems.org.

```
gem 'sinatra', '~> 1.0'
```

I'll look into upgrading this gem once sinatra 2.0.0 stable is released.
